name: build

on:
    push:
        branches:
        - ci
        tags:
        - v*

env:
    CARGO_TERM_COLOR: always

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
        - uses: actions-rs/cargo@v1
          with:
            command: check

    x86_64-unknown-linux-gnu:
        needs: [check]
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
        - uses: actions-rs/cargo@v1
          with:
            command: build
            args: --release --target x86_64-unknown-linux-gnu
        - uses: actions/upload-artifact@v2
          with:
            name: pihole-influx-agent-x86_64-unknown-linux
            path: ./target/x86_64-unknown-linux-gnu/release/pihole-influx-agent
