name: build

on:
    push:
        tags:
        - v*
env:
    CARGO_TERM_COLOR: always

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
        - uses: actions-rs/cargo@v1
          with:
            command: check
    #create-release:
        #runs-on: ubuntu-latest
        #steps:
        #- uses: actions/create-release@v1
          #id: create_release
          #with:
            #draft: false
            #prerelease: false
            #release_name: ${{ github.ref_name }}
            #tag_name: ${{ github.ref_name }}

    x86_64-unknown-linux-gnu:
        needs: [check]
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
        - uses: actions-rs/cargo@v1
          with:
            command: build
            args: --release --target x86_64-unknown-linux-gnu
        - uses: softprops/action-gh-release@v1
          with:
            files: 'target/x86_64-unknown-linux-gnu/release/pihole-influx-agent'
