name: build

on:
    push:
      branches:
        - ci

env:
    CARGO_TERM_COLOR: always

jobs:
    x86_64-unknown-linux-gnu:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
        - uses: actions-rs/cargo@v1
          with:
            command: build
            args: --release --target x86_64-unknown-linux-gnu
        - uses: actions/upload-artifact@v2
          with:
            name: pihole-influx-agent-target-x86_64-unknown-linux
            path: ./target/x86_64-unknown-linux-gnu/release/pihole-influx-agent
